version: "3.0"
services:
  kanban:
    build: ./
    volumes:
      - ./src:/var/www
    ports:
      - 64729:80
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
  mysql:
    image: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password